### PR TITLE
update RTD links

### PR DESCRIPTION
**Pull request by nstarman**
This should be a v0.1.1 release, fixing the RTD links.

### CODE REVIEW

**Comment by nstarman** [comment]
@ntessore the docs are having some compilation issues.

**Comment by ntessore** [comment]
Seems like the hook didn't fire properly, because the [build succeeded](https://readthedocs.org/projects/cosmologyapi/builds/21878604/).

**Comment by ntessore** [comment]
Checked the hook, looks ok. You could try amending the commit with `--date=now` and force-pushing to get another docs build going?

**Comment by ntessore** [comment]
Ok, there were also some issues due to the renaming of the projects. The old `cosmology` RTD check was required, but RTD's build is called `cosmologyapi` now.

**Pull request merged**
